---
title: "MSPMS-Shiny"
author: "Charlie Bayne"
date: "`r Sys.Date()`"
output:
  html_document:
        theme: cosmo
        highlight: tango
        df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
ggplot2::theme_set(ggprism::theme_prism(palette = "viridis"))
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# About 

This is a Shiny app designed to use the [mspms R package](https://github.com/baynec2/mspms) to analyze data from the [Multiplex Substrate Profiling by Mass Spectrometry (MSP-MS) method](https://pubmed.ncbi.nlm.nih.gov/36948708/)

# How to use

On the side bar, you will see three places to upload files.  

1. The first file should be the LFQ file as exported from PEAKS. This file should be a csv file.  

2. The second file should be the ID file as exported from PEAKS. This file should also be a csv file.  

3. The third file should be the design matrix file. This should be a csv file.  

The design matrix file should be a csv file with the following columns: "sample", "group","condition","time". The sample column should contain the names of the samples as found in the PEAKS files. The group column should contain the group that the sample belongs to. This can be any thing, as long as it is the same per group. The time column should contain the duration of incubation, and the condition column should include any experimental condition such as protease inhibitor. 


You will also see four tabs at the side of the page, About, Output, Stats, and DataViz  

About links to the instructions shown here   

Output contains a rendering of the normalized data, and a button that says download. This button will allow you to download the data that has been processed as a .csv file.  

Be patient with the output tab, it takes a while for the code to execute. When it is finished, the table will appear and the data will be ready for download. 

Stats contains a table of the results of the t-tests and ANOVA tests. Be patient, when it is finished the talbe will appear and the data will be ready for download.

DataViz contains a PCA plot, heatmap of the data, and volcano plots of all the data.  Be patient,this takes a while to render. 






