#' plot_qc_check
#
#' plot the qc results generated by the qc_check function to show metrics about
#' the percent of the library detected per sample group.
#' @param qc_check_data qc check results produced by the qc_check function
#' @param threshold_percent percent to use as threshold visualized as red
#'  dashed line
#' @param ncol n columns.
#' @return a list containing 2 ggplot objects. The first slot contains plot of
#' percent of the full length peptides detected per sample group, the second
#' slot contains the percent of library mapped to per sample group (includes
#' full length and cleaved peptides)
#' @export
#'
#' @examples
#' qc_check <- qc_check(
#'   mspms::prepared_data,
#'   mspms::peptide_library,
#'   mspms::design_matrix
#' )
#'
#' plot_qc_check(qc_check)
plot_qc_check <- function(qc_check_data, thresold_percent = 90,ncol = 1) {
  p1 <- qc_check_data %>%
    ggplot2::ggplot() +
    ggplot2::geom_histogram(ggplot2::aes_string("perc_undigested_library_detected"), binwidth = 0.1) +
    ggplot2::geom_density(ggplot2::aes_string("perc_undigested_library_detected")) +
    ggplot2::geom_vline(xintercept = thresold_percent, linetype = "dashed", color = "red") +
    ggplot2::facet_wrap(~group, scales = "free_y",ncol = ncol) +
    ggplot2::ggtitle("Percent of Full Length Library Detected") +
    ggplot2::ylab("count")


  p2 <- qc_check_data %>%
    ggplot2::ggplot() +
    ggplot2::geom_histogram(ggplot2::aes_string("perc_library_detected"), binwidth = 0.1) +
    ggplot2::geom_density(ggplot2::aes_string("perc_library_detected")) +
    ggplot2::geom_vline(xintercept = thresold_percent, linetype = "dashed", color = "red") +
    ggplot2::facet_wrap(~group, scales = "free_y",ncol = ncol) +
    ggplot2::ggtitle("Percent of Library Mapped to") +
    ggplot2::ylab("count")

  out <- list(p1, p2)

  return(out)
}
