#' prepare_fragpipe
#' 
#' Prepare a label free quantification file exported from Fragpipe
#' for subsequent mspms analysis.
#'
#' @param combined_peptide_filepath file path the combined_peptide.tsv file
#' generated by FragPipe.
#' @param colData tibble containing colData (sample metadata). Must have
#' columns named "quantCols","group","condition",and "time". 
#' @param peptide_library peptide library contained in the experiment 
#' @param n_residues the number of amino acid residues before and after the
#' cleavage site to generate a cleavage seq for.
#'
#' @return a QFeatures object containing a summarizedExperiment named "peptides" 
#' @export
#'
#' @examples
#' colData = readr::read_csv("inst/extdata/colData.csv")
#' combined_peptide_filepath = "inst/extdata/fragpipe_combined_peptide.tsv"
#' prepared_fragpipe_data = prepare_fragpipe(combined_peptide_filepath)
prepare_fragpipe = function(combined_peptide_filepath,
                            colData,
                            peptide_library = mspms::peptide_library,
                            n_residues = 4){
  # Reading in the label free quantification data
  lfq <- readr::read_tsv(combined_peptide_filepath,na = c("-",0,"","NA")) 
  # Check that this file appears to be a proper fragpipe file
  check_file_is_valid_fragpipe(lfq)
  
  # Reformat the columns to be consistent with mspsms framework
  lfq_mod = lfq %>% 
    dplyr::mutate(`Prev AA` = dplyr::case_when(is.na(`Prev AA`) ~ "",
                                               TRUE ~ `Prev AA`)) %>% 
    dplyr::mutate(`Next AA` = dplyr::case_when(is.na(`Next AA`) ~ "",
                                               TRUE ~ `Next AA`)) %>% 
    dplyr::mutate(peptide = paste0(`Prev AA`,"_",
                                   `Peptide Sequence`,"_",`Next AA`),
                  .before =1) %>% 
    dplyr::mutate(peptide = gsub("^_","",peptide),
                  peptide = gsub("_$","",peptide)) %>% 
    dplyr::select(peptide,library_id = "Protein",
                  dplyr::contains("MaxLFQ Intensity")) %>% 
    dplyr::rename_with(
      ~stringr::str_replace_all(.,"MaxLFQ Intensity",""))
  
  # Converting 0 to NA
  lfq_mod[lfq_mod == 0] <- NA
                
  
  # converting into QF object
  fragpipe_prepared_qf = mspms:::prepared_to_qf(lfq_mod,colData,
                                        peptide_library,n_residues)
  return(fragpipe_prepared_qf)
}


